In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['font.size'] = 16
plt.rcParams['figure.figsize'] = 20, 10
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
# 지표를 하나만 설정할 경우
from sklearn.model_selection import cross_val_score
# 지표를 하나 이상 설정할 경우
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 모델의 최적의 하이퍼파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집화
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth

# ARIMA (시계열 예측)
from statsmodels.tsa.arima_model import ARIMA
import statsmodels.api as sm

# 시간 측정을 위한 시간 모듈
import datetime
# 주식 정보를 읽어오기 위한 라이브러리
from pandas_datareader import data

# 형태소 백터를 생성하기 위한 라이브러리
from sklearn.feature_extraction.text import CountVectorizer
# 형태소 백터를 학습 백터로 변환한다.
from sklearn.feature_extraction.text import TfidfTransformer

# 데이터 수집
import requests
from bs4 import BeautifulSoup
import re
import time
import os
import json

# 한국어 형태소 분석
from konlpy.tag import Okt, Hannanum, Kkma, Mecab, Komoran

# 워드 클라우드를 위한 라이브러리
from collections import Counter
import pytagcloud
from IPython.display import Image

# 출력 창 청소를 위한 함수
from IPython.display import clear_output

# 저장
import pickle

# 딥러닝
import tensorflow as tf

# 딥러닝 모델 구조를 정의하는 것
from tensorflow.keras.models import Sequential
# 층구조를 정의하는 것
from tensorflow.keras.layers import Dense
# 활성화 함수를 정의하는 것
from tensorflow.keras.layers import Activation

# 다중 분류를 위한 원핫 인코딩
# 결과데이터의 종류 수 만큼 결과데이터의 컬럼을 늘리는 작업
from tensorflow.keras.utils import to_categorical

# 현재 프로젝트를 gpu에 할당한다.
# 컴퓨터의 GPU는 메모리를 가지고 있다.
gpus = tf.config.experimental.list_physical_devices('GPU')
# gpu가 있다면..
if len(gpus) > 0 :
    try :
        for gpu in gpus :
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e :
        print(e)

pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
# 랜덤 시드 설정
tf.random.set_seed(1)

In [3]:
# 데이터를 읽어온다.
df1 = pd.read_csv('data/iris.csv', header=None)
df1.columns = ['꽃받침길이', '꽃받침너비', '꽃잎길이', '꽃잎너비', '품종']
df1.head()

꽃받침길이  꽃받침너비  꽃잎길이  꽃잎너비           품종
0    5.1    3.5   1.4   0.2  Iris-setosa
1    4.9    3.0   1.4   0.2  Iris-setosa
2    4.7    3.2   1.3   0.2  Iris-setosa
3    4.6    3.1   1.5   0.2  Iris-setosa
4    5.0    3.6   1.4   0.2  Iris-setosa

In [4]:
# 입력과 결과로 나눈다.
X = df1.drop('품종', axis=1)
y = df1['품종']

display(X)
display(y)

꽃받침길이  꽃받침너비  꽃잎길이  꽃잎너비
0      5.1    3.5   1.4   0.2
1      4.9    3.0   1.4   0.2
2      4.7    3.2   1.3   0.2
3      4.6    3.1   1.5   0.2
4      5.0    3.6   1.4   0.2
..     ...    ...   ...   ...
145    6.7    3.0   5.2   2.3
146    6.3    2.5   5.0   1.9
147    6.5    3.0   5.2   2.0
148    6.2    3.4   5.4   2.3
149    5.9    3.0   5.1   1.8

[150 rows x 4 columns]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: 품종, Length: 150, dtype: object

In [5]:
# 문자열로 되어 있는 데이터를 숫자로 변환한다.
encoder1 = LabelEncoder()
encoder1.fit(y)
y = encoder1.transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
# 원핫인코딩.
# 분류의 경우에는 결과 데이터가 0부터 1씩 증가되는 형태라고 하더라도
# 연속성을 가진 데이터가 아닌 각각의 별개의 데이터를 의미한다.
# 딥러닝은 무조건 회귀를 한다. 이에 분류인 경우에는 결과 값을 보고 if 문으로
# 분기해서 결과를 우리가 직접 파악해야 한다. 하지만 원핫 인코딩을 쓰게 되면
# 결과데이터의 수 만큼 컬럼이 생성되고 각 컬럼은 0 아니면 1만 들어가 있게 
# 된다. 향후 최종 각 컬럼에 담겨져 있는 값중 가장 큰값의 인덱스를 가져오면
# 그것이 결과 데이터가 될 수 있다.
y_encoded = to_categorical(y)
y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

#### 이진 분류
- 결과가 두 가지인 경우
- 출력층의 노드를 1로 설정한다.
- 출력층의 활성 함수는 sigmoid로 설정한다.
- compile시 손실함수는 binary_crossentropy로 설정한다.

#### 다중 분류
- 결과가 두 가지  이상인 경우(3가지 이상인 경우에 해주세요)
- 원핫 인코딩을 해야 하기 때문에 출력층의 노드 개수는 결과 데이터의 종류 수로 설정한다.
- 출력층의 활성 함수는 softmax로 설정한다.
- compile시 손실함수는 categorical_crossentropy로 설정한다.

In [7]:
# 모델 설계
model = Sequential()

model.add(Dense(16, input_dim=4))
model.add(Activation('relu'))

# 다중 분류의 출력층의 노드 개수는 결과 데이터의 종류의 개수로 설정해야 한다.
model.add(Dense(3))
model.add(Activation('softmax'))

In [8]:
# 모델 컴파일
# 다중 분류인 경우에는 손실함수를 categorical_crossentropy로 설정한다.
model.compile(loss='categorical_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [9]:
# 학습한다.
model.fit(X, y_encoded, epochs=50, batch_size=10)

Epoch 1/50
15/15 [==============================] - 1s 2ms/step - loss: 2.3569 - accuracy: 0.3333
Epoch 2/50
15/15 [==============================] - 0s 2ms/step - loss: 1.6622 - accuracy: 0.3333
Epoch 3/50
15/15 [==============================] - 0s 2ms/step - loss: 1.2693 - accuracy: 0.4267
Epoch 4/50
15/15 [==============================] - 0s 2ms/step - loss: 1.0222 - accuracy: 0.6600
Epoch 5/50
15/15 [==============================] - 0s 2ms/step - loss: 0.9085 - accuracy: 0.6667
Epoch 6/50
15/15 [==============================] - 0s 2ms/step - loss: 0.8346 - accuracy: 0.7667
Epoch 7/50
15/15 [==============================] - 0s 2ms/step - loss: 0.7869 - accuracy: 0.9267
Epoch 8/50
15/15 [==============================] - 0s 2ms/step - loss: 0.7470 - accuracy: 0.9600
Epoch 9/50
15/15 [==============================] - 0s 2ms/step - loss: 0.7100 - accuracy: 0.9533
Epoch 10/50
15/15 [==============================] - 0s 2ms/step - loss: 0.6795 - accuracy: 0.9133
Epoch 11/50
15/15 [

In [10]:
# 예측 정확도
# 주어진 입력 데이터를 통해 예측 결과를 도출하고 설정한 결과 데이터와 
# 비교해서 얼마나 일치하는지 확인한다.
a1 = model.evaluate(X, y_encoded)
print(f'손실률 : {a1[0]}')
print(f'정확도 : {a1[1]}')

5/5 [==============================] - 0s 2ms/step - loss: 0.2827 - accuracy: 0.9733
손실률 : 0.28273600339889526
정확도 : 0.9733333587646484


In [11]:
# 2021-1-1 일 이후 언젠가는 제거될 예정
# pred = model.predict_classes(X)
# pred

In [14]:
# 결과를 가져온다.
pred = np.argmax(model.predict(X), axis=-1)
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [15]:
# 결과 문자열로 디코딩한다.
y_pred = encoder1.inverse_transform(pred)
y_pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [17]:
# 정확도 확인
r1 = accuracy_score(df1['품종'], y_pred)
r1

0.9733333333333334